# Site settings
author: Burak Kocak
title: My First Portfolio Project
header-img: img/home-bg.png
email: burakkocak884@hotmail.com
copyright_name: Burak Kocak
description: > # this means to ignore newlines until "baseurl:"
  Fifa Worldcup User App
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  burakkocak884

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
